services:
  mysql:
    image: mysql:8
    container_name: mediavault-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mediavault
      MYSQL_USER: mediavault_user
      MYSQL_PASSWORD: mediavault_pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    build: ./backend
    container_name: mediavault-backend
    restart: always
    working_dir: /code
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    command: ["/entrypoint.sh", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mediavault-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: mediavault_user
      PMA_PASSWORD: mediavault_pass
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  dbdata:
