"""init schema

Revision ID: a9c40321c5f2
Revises: af9e1e172e1e
Create Date: 2025-09-11 18:32:29.890222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9c40321c5f2'
down_revision: Union[str, Sequence[str], None] = 'af9e1e172e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('BOOKED', 'COMPLETED', 'CANCELLED', name='appointmentstatus'),
               existing_nullable=True)
    op.alter_column('appointments', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('expenses', 'category',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('CONSULTATION', 'MEDICINE', 'LAB', 'OTHER', name='expensecategory'),
               existing_nullable=True)
    op.alter_column('expenses', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('prescriptions', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('records', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('records', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('prescriptions', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('expenses', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('expenses', 'category',
               existing_type=sa.Enum('CONSULTATION', 'MEDICINE', 'LAB', 'OTHER', name='expensecategory'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('appointments', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('appointments', 'status',
               existing_type=sa.Enum('BOOKED', 'COMPLETED', 'CANCELLED', name='appointmentstatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
